---
DEBUG: true
SQLALCHEMY_DATABASE_URI: sqlite:///C:/Users/Gregor/Documents/Programming/square-core/square-backend/app.db
SQLALCHEMY_TRACK_MODIFICATIONS: false
JWT_IDENTITY_CLAIM: sub
JWT_SECRET_KEY: change this key to something else
JWT_ACCESS_TOKEN_EXPIRES: 10000
skillSelector:
  selectors:
    - name: base
      config: {}
