#@data/values
---
environment: local #! set this to 'local' or 'prod'
os: mac #! set this to 'linux', 'mac' or 'windows'
email: baumgaertner.t@gmail.com

skills:
  - name: boolq
  - name: commonsense-qa
  - name: squad-v2
  - name: open-bioasq
  - name: open-squad
  - name: extractive-qa
  - name: multiple-choice-qa
  - name: generative-qa
  - name: open-extractive-qa

web_concurrency: 2

verify_ssl:
  prod: 1
  local: 0

square_api_url: 
  prod: https://square.ukp-lab.de/api
  local: https://host.docker.internal/api

keycloak_base_url:
  prod: square.ukp-lab.de
  local: square.ukp-lab.local

keycloak_base_url_https:
  prod: https://square.ukp-lab.de
  local: https://square.ukp-lab.local

faiss_url:
  prod: https://square.ukp-lab.de/api
  local: https://localhost/api

model_url:
  prod: https://square.ukp-lab.de/api
  local: https://localhost/api

docker_host_url:
  windows: http://host.docker.intneral
  mac: http://host.docker.intneral
  linux: https://172.17.0.1
