#@data/values
---
environment: "prod"
skills:
  - name: boolq
    port: "8001"
  - name: commonsense-qa
    port: "8002"
  - name: squad-v2
    port: "8003"
  - name: open-bioasq
    port: "8004"
  - name: open-squad
    port: "8005"
  - name: extractive-qa
    port: "8006"
  - name: multiple-choice-qa
    port: "8007"
