#@data/values
---
skills:
  - name: boolq
    port: "8001"
  - name: commonsense-qa
    port: "8002"
  - name: squad-v2
    port: "8003"
  - name: open-bioasq
    port: "8004"
  - name: open-squad
    port: "8005"
  - name: extractive-qa
    port: "8006"
  - name: multiple-choice-qa
    port: "8007"

environment: "local"
os: "linux"

square_api_url: 
  prod: https://square.ukp-lab.de/api
  local: https://host.docker.internal/api

keycloak_base_url:
  prod: https://square.ukp-lab.de
  local: http://localhost:8080

verify_ssl:
  prod: 1
  local: 0

faiss_url:
  prod: https://square.ukp-lab.de/api
  local: https://localhost/api

model_url:
  prod: https://square.ukp-lab.de/api
  local: https://localhost/api

docker_host_url:
  windows: http://host.docker.intneral
  mac: http://host.docker.intneral
  linux: https://172.17.0.1

web_concurrency: 2
