version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbpw
      - POSTGRES_USER=square
      - POSTGRES_DB=square
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: ukpsquare/square-backend:latest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - migrations-data:/app/migrations

  frontend:
    image: ukpsquare/square-frontend:latest
    restart: always
    ports:
      - 80:80

### Skills
  naturalqa_retrieve_span_skill:
    build: ./skills/naturalqa-retrieve-span-skill/.
    ports:
      - 8777:8000
    env_file:
      - ./skills/naturalqa-retrieve-span-skill/.env
    volumes:
      - ./skills/naturalqa-retrieve-span-skill/skillapi/:/app/skillapi #for developement
      - ./skills/naturalqa-retrieve-span-skill/tests/data_api_response.json:/app/tests/data_api_response.json

### MODEL API
  model_auth:
    image: ukpsquare/square-model-api-auth:latest
    env_file:
      - ./square-model-inference-api/auth_server/.env

  model_nginx:
    image: nginx
    ports:
      - 8989:8080
    volumes:
      - ./square-model-inference-api/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  model_bert_adapter:
    image: ukpsquare/square-model-api:latest
    env_file:
      - ./square-model-inference-api/inference_server/.env.bert_adapter
    volumes:
      - ./.cache/:/etc/huggingface/.cache/

  model_dpr:
    image: ukpsquare/square-model-api:latest
    env_file:
      - ./square-model-inference-api/inference_server/.env.dpr
    volumes:
      - ./.cache/:/etc/huggingface/.cache/

### / MODEL API Finished

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080

  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - es01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200

volumes:
  db-data:
    driver: local
  migrations-data:
    driver: local
  es01:
    driver: local
