version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbpw
      - POSTGRES_USER=square
      - POSTGRES_DB=square
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: ukpsquare/square-backend:latest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - migrations-data:/app/migrations

  frontend:
    image: ukpsquare/square-frontend:latest
    restart: always
    ports:
      - 80:80

### MODEL API
  model_auth:
    image: ukpsquare/square-model-api-auth:latest
    env_file:
      - ./square-model-inference-api/auth_server/.env

  model_nginx:
    image: nginx
    ports:
      - 8989:8080
    volumes:
      - ./square-model-inference-api/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  model_bert_adapter:
    image: ukpsquare/square-model-api:latest
    env_file:
      - ./square-model-inference-api/inference_server/.env.bert_adapter
    volumes:
      - ./.cache/:/etc/huggingface/.cache/

  model_dpr:
    image: ukpsquare/square-model-api:latest
    env_file:
      - ./square-model-inference-api/inference_server/.env.dpr
    volumes:
      - ./.cache/:/etc/huggingface/.cache/

### / MODEL API Finished

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080

  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - es01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200

 ### DATASTORE API
  vespa:
    image: vespaengine/vespa
    container_name: vespa
    hostname: vespa-container
    privileged: true
    ports:
      - "8082:8080"
      - "19071:19071"
    volumes:
      - ./storage/vespa/var:/opt/vespa/var
      - ./storage/vespa/logs:/opt/vespa/logs

  mongodb:
    image: mongo:4.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./storage/db/data:/data/db

### DATASTORE API - Finished

  # datastore_api:
  #   privileged: true
  #   build: .
  #   depends_on:
  #     - vespa
  #     - mongodb
  #   ports:
  #     - "8002:8000"
  #   environment:
  #     - VESPA_CONFIG_URL=http://vespa:19071
  #     - VESPA_APP_URL=http://vespa:8082
  #     - MONGODB_URL=mongodb://root:root@mongodb:27017/admin?retryWrites=true&w=majority
  #     # Specify Model API
  #     # - MODEL_API_URL=http://localhost:9000/api

volumes:
  db-data:
    driver: local
  migrations-data:
    driver: local
  es01:
    driver: local
