version: "3.1"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es01
    environment:
      - discovery.type=single-node
    volumes:
      - ./storage/es/data:/usr/share/elasticsearch/data
    ports:
      - 7200:9200

  reverse-proxy:
      image: traefik:v2.5
      # Enables the web UI and tells Traefik to listen to docker
      command:
        - "--api.insecure=true"
        - "--providers.docker"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:7010"
      ports:
        # The HTTP port
        - "7010:7010"
        # The Web UI (enabled by --api.insecure=true)
        - "7070:8080"
      volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.prefix-strip.stripprefixregex.regex=(/[^/]+){2}"

  faiss-rest-1:
    image: kwang2049/faiss-instant:latest
    container_name: faiss-rest-1
    volumes:
      - ./resources/wiki:/opt/faiss-instant/resources
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5000"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=PathPrefix(`/wiki/dpr`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=prefix-strip"

  faiss-rest-2:
    image: kwang2049/faiss-instant:latest
    container_name: faiss-rest-2
    volumes:
      - ./resources/wiki2:/opt/faiss-instant/resources
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5000"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=PathPrefix(`/wiki2/dpr`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=prefix-strip"

  # datastore_api:
  #   privileged: true
  #   build: .
  #   depends_on:
  #     - vespa
  #     - mongodb
  #   ports:
  #     - "7000:7000"
  #   environment:
  #     - VESPA_CONFIG_URL=http://vespa:19071
  #     - VESPA_APP_URL=http://vespa:8080
  #     - MONGODB_URL=mongodb://root:root@mongodb:27017/admin?retryWrites=true&w=majority
  #     # Specify Model API
  #     - MODEL_API_URL=http://localhost:8000/api