version: "3.1"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01
    environment:
      - discovery.type=single-node
    volumes:
      - ./storage/es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # datastore_api:
  #   privileged: true
  #   build: .
  #   depends_on:
  #     - vespa
  #     - mongodb
  #   ports:
  #     - "7000:7000"
  #   environment:
  #     - VESPA_CONFIG_URL=http://vespa:19071
  #     - VESPA_APP_URL=http://vespa:8080
  #     - MONGODB_URL=mongodb://root:root@mongodb:27017/admin?retryWrites=true&w=majority
  #     # Specify Model API
  #     - MODEL_API_URL=http://localhost:8000/api