version: "3"

services:
#  auth:
#    #build: ./auth_server/.
#    image: ukpsquare/square-model-api-auth:latest
#    # Portforwarding not needed
##    ports:
##      - 8081:8081
#    env_file:
#      - ./auth_server/.env.example

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.filename=/config/traefik.yaml
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.http.middlewares=prefix-strip@file, auth@file
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./inference_server/traefik.yaml:/config/traefik.yaml

  # Example config for one model server
  inference_bert:
    #build: ./inference_server/.
    image: ukpsquare/square-model-api:latest
    # Portforwarding not needed
#    ports:
#      - 8000:8000
    env_file:
      - inference_server/.env
    volumes:
      - ./.cache/:/etc/huggingface/.cache/
      #- ./inference_server/:/app/ #for developement
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bert.rule=PathPrefix(`/bert`)"

    # Example config for another model server
  inference_roberta:
    #build: ./inference_server/.
    image: ukpsquare/square-model-api:latest
    # Portforwarding not needed
    #    ports:
    #      - 8001:8000
    env_file:
      - ./inference_server/.env.roberta
    volumes:
      - ./.cache/:/etc/huggingface/.cache/
      #- ./inference_server/:/app/ #for developement

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roberta.rule=PathPrefix(`/roberta`)"