name: Build

on:
  push:
    branches: [ master, cicd ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        service: [
          "datastore", 
          "docs", 
          "frontend", 
          "model-management", 
          "model-inference", 
          "skill-manager", 
          "skill-boolq",
          "skill-commonsense-qa",
          "skill-extractive-qa",
          "skill-generative-qa",
          "skill-information-retrieval",
          "skill-multiple-choice-qa",
          "skill-open-extractive-qa",
          "skill-qa-gnn",
        ]
        include:
          - service: datastore
            context: ./datastore-api
          - service: docs
            context: ./docs
          - service: frontend
            context: ./frontend
          - service: model-management
            context: ./square-model-inference-api/management_server
          - service: model-inference
            context: ./square-model-inference-api/inference_server
          - service: skill-manager
            context: ./skill-manager
          - service: skill-boolq
            context: ./skills
          - service: skill-commonsense-qa
            context: ./skills
          - service: skill-extractive-qa
            context: ./skills
          - service: skill-generative-qa
            context: ./skills
          - service: skill-information-retrieval
            context: ./skills
          - service: skill-multiple-choice-qa
            context: ./skills
          - service: skill-open-extractive-qa
            context: ./skills
          - service: skill-qa-gnn
            context: ./skills
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-
            ${{ runner.os }}-buildx-

      - name: Build deployable image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.context }}
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ukpsquare/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      #  Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
