name: CD

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.TEST_VM_WEBHOOK_URL }}
        webhook_secret: ${{ secrets.TEST_VM_WEBHOOK_SECRET }}
        verify_ssl: false  
