name: "CI Datastore"

on:
  push:
    branches: [ master ]
    paths:
      - "datastore-api/**"
      - ".github/**"
  pull_request:
    branches: [ master ]
    paths:
      - "datastore-api/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  datastore-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-datastore-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-datastore-
            ${{ runner.os }}-buildx-

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./datastore-api
          target: test
          load: true
          tags: datastore:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Run test image
        uses: addnab/docker-run-action@v3
        with:
          image: datastore:${{ github.sha }}
          options: -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}/datastore-api/test-reports:/app/test-reports
          run: |
            PYTHONPATH="." MOCK_DEPENDENCIES=1 pytest --junitxml=test-reports/junit.xml --cov --cov-report=xml:test-reports/coverage.xml --cov-report=html:test-reports/coverage.html ./tests

      - uses: actions/upload-artifact@v2
        with:
          name: datastore_api-test-reports
          path: ${{ steps.extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          # report_paths: ${{ steps.extract.outputs.destination }}/test-reports/junit.xml
          report_paths: ${{ github.workspace }}/datastore-api/test-reports/junit.xml
          check_name: Datastore API Test Report
          fail_on_failure: true

      #  Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
