name: "CI Model API"

on:
  push:
    branches: [ model-api-v3 ]
    paths:
      - "square-model-inference-api/**"
      - ".github/**"
  pull_request:
    branches: [ master ]
    paths:
      - "square-model-inference-api/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  model-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: base-prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-model-api-base-model"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: base-buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-model_api-
            ${{ runner.os }}-buildx-

      - name: Build base test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.base-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/base_model/Dockerfile
          target: test
          load: true
          tags: ${{ steps.base-prep.outputs.image }}:${{ steps.base-prep.outputs.tag }}-test
#          no-cahce: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Retrieve Test Reports
        id: base-extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.base-prep.outputs.image }}:${{ steps.base-prep.outputs.tag }}-test
          path: /inference_api/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.base-extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.base-extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build base deployable image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.base-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/base_model/Dockerfile
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ${{ steps.base-prep.outputs.image }}:${{ steps.base-prep.outputs.tag }}, ${{ steps.base-prep.outputs.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      #  Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: remove images
        run: |
          docker kill $(docker ps -q)
          docker rm -f $(docker ps -a -q)
          docker image rm -f $(docker images -q)

##################################
      - name: Prepare
        id: transformer-prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-model-api-transformer"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: transformer-buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-model_api-
            ${{ runner.os }}-buildx-

      - name: Build transformer test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.transformer-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/transformer/Dockerfile
          target: test
          load: true
          tags: ${{ steps.transformer-prep.outputs.image }}:${{ steps.transformer-prep.outputs.tag }}-test
#          no-cahce: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Retrieve Test Reports
        id: transformer-extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.transformer-prep.outputs.image }}:${{ steps.transformer-prep.outputs.tag }}-test
          path: /inference_api/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.transformer-extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.transformer-extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build transformer deployable image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.transformer-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/transformer/Dockerfile
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ${{ steps.transformer-prep.outputs.image }}:${{ steps.transformer-prep.outputs.tag }}, ${{ steps.transformer-prep.outputs.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      #  Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: remove images
        run: |
          docker kill $(docker ps -q)
          docker rm -f $(docker ps -a -q)
          docker image rm -f $(docker images -q)

      # sentence-transformers
      - name: Prepare
        id: sentence-transformer-prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-model-api-sentence-transformer"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: sentence-transformer-buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-model_api-
#            ${{ runner.os }}-buildx-

      - name: Build  sentence-transformers test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.sentence-transformer-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/sentence_transformer/Dockerfile
          target: test
          load: true
          tags: ${{ steps.sentence-transformer-prep.outputs.image }}:${{ steps.sentence-transformer-prep.outputs.tag }}-test
#          no-cahce: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Retrieve Test Reports
        id: sentence-transformer-extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.sentence-transformer-prep.outputs.image }}:${{ steps.sentence-transformer-prep.outputs.tag }}-test
          path: /inference_api/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.sentence-transformer-extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.sentence-transformer-extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build sentence-transformers deployable image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.sentence-transformer-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/sentence_transformer/Dockerfile
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ${{ steps.sentence-transformer-prep.outputs.image }}:${{ steps.sentence-transformer-prep.outputs.tag }}, ${{ steps.sentence-transformer-prep.outputs.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: remove images
        run: |
          docker kill $(docker ps -q)
          docker rm -f $(docker ps -a -q)
          docker image rm -f $(docker images -q)

      # onnx
      - name: Prepare
        id: onnx-prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-model-api-onnx"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: onnx-buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-model_api-
#            ${{ runner.os }}-buildx-

      - name: Build onnx test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.onnx-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/onnx/Dockerfile
          target: test
          load: true
          tags: ${{ steps.onnx-prep.outputs.image }}:${{ steps.onnx-prep.outputs.tag }}-test
#          no-cahce: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Retrieve Test Reports
        id: onnx-extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.onnx-prep.outputs.image }}:${{ steps.onnx-prep.outputs.tag }}-test
          path: /inference_api/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.onnx-extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.onnx-extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build onnx deployable image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.onnx-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/onnx/Dockerfile
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ${{ steps.onnx-prep.outputs.image }}:${{ steps.onnx-prep.outputs.tag }}, ${{ steps.onnx-prep.outputs.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: remove images
        run: |
          docker kill $(docker ps -q)
          docker rm -f $(docker ps -a -q)
          docker image rm -f $(docker images -q)


      # graph- transformer
      - name: Prepare
        id: graph-prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-model-api-graph-transformer"
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: graph-buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-model_api-
#            ${{ runner.os }}-buildx-

      - name: Build graph test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.graph-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/graph_transformer/Dockerfile
          target: test
          load: true
          tags: ${{ steps.graph-prep.outputs.image }}:${{ steps.graph-prep.outputs.tag }}-test
#          no-cahce: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Retrieve Test Reports
        id: graph-extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.graph-prep.outputs.image }}:${{ steps.graph-prep.outputs.tag }}-test
          path: /inference_api/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.graph-extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.graph-extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build graph deployable image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.graph-buildx.outputs.name }}
          context: ./square-model-inference-api/inference_api
          file: ./square-model-inference-api/inference_api/dockerfiles/graph_transformer/Dockerfile
          target: build
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ${{ steps.graph-prep.outputs.image }}:${{ steps.graph-prep.outputs.tag }}, ${{ steps.graph-prep.outputs.image }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
