name: "CI Model"

on:
  push:
    branches: [ master ]
    paths:
      - "square-model-inference-api/**"
      - ".github/**"
  pull_request:
    branches: [ master ]
    paths:
      - "square-model-inference-api/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  model-inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-model_api-
            ${{ runner.os }}-buildx-

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./square-model-inference-api/inference_server
          target: test
          load: true
          tags: model-inference:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Retrieve Test Reports
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: model-inference:${{ github.sha }}
          path: /app/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      #  Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  model-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-model_api-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-model-management-
            ${{ runner.os }}-buildx-

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./square-model-inference-api/management_server
          target: test
          load: true
          tags: model-management:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Retrieve Test Reports
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.tag }}-test
          path: /app/test-reports

      - uses: actions/upload-artifact@v2
        with:
          name: model_api-test-reports
          path: ${{ steps.extract.outputs.destination }}/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.extract.outputs.destination }}/test-reports/junit.xml
          check_name: Model API Test Report
          fail_on_failure: true

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
