name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
          - 'test'
          - 'prod'
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'
  release:
    types: [ published ]
    inputs:
      environment:
        value: 'prod'
      branch:
        value: 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.sha }}
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Trigger Deployment on ${{ github.event.inputs.environment }}
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"branch": "${{ github.event.inputs.branch }}", "sha": "${{ github.sha }}"}'
          verify_ssl: false
