name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="ukpsquare/square-backend"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG} 
          echo ::set-output name=image::${IMAGE}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./square-backend
          target: test
          load: true
          tags: ${{ steps.prep.outputs.tagged_image }}-test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      
      
       # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - run: |
          docker image ls
        
      - name: Retrieve Test Reports
        id: extract
        uses: shrink/actions-docker-extract@v1
        with:
          image: ${{ steps.prep.outputs.tagged_image }}-test
          path: /app/test-reports

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ${{ steps.extract.outputs.destination }}/test-reports/junit.xml

      - name: Check Test Result
        run: if [ $(cat ${{ steps.extract.outputs.destination }}/test-reports/pytest.exitcode) != 0 ]; then exit 1; fi  

      - name: Build test image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./square-backend
          target: build
          push: true
          image: ${{ steps.prep.outputs.image }}
          tags: ${{ steps.prep.outputs.tag }}, latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      #  Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: github.ref == 'refs/heads/master'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
